# Generated by Django 4.0.4 on 2022-05-23 08:08

from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_create_homepage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homepage',
            options={'verbose_name': 'Home page'},
        ),
        migrations.AddField(
            model_name='homepage',
            name='content',
            field=wagtail.fields.StreamField([('paragraph', wagtail.blocks.StructBlock([('content', wagtail.blocks.StreamBlock([('media', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(max_length=255)), ('description', wagtail.blocks.TextBlock())]))], label='Paragraph', max_num=2, min_num=2))]))], blank=True, null=True, use_json_field=None, verbose_name='Content'),
        ),
    ]
