# Generated by Django 4.0.4 on 2022-05-23 21:37

from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_homepage_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='content',
            field=wagtail.fields.StreamField([('paragraph', wagtail.blocks.StructBlock([('content', wagtail.blocks.StreamBlock([('paragraph', wagtail.blocks.StructBlock([('description', wagtail.blocks.RichTextBlock(''))]))], label='Paragraph'))]))], blank=True, null=True, use_json_field=None, verbose_name='Content'),
        ),
    ]
